const assert=require('assert');
const fs=require('fs');
const ui=fs.readFileSync('operations-ui.js','utf8');
const ops=fs.readFileSync('class-ops-canonical.js','utf8');
const planner=fs.readFileSync('management-planner.js','utf8');
const editor=fs.readFileSync('calendar-class-editor.js','utf8');
const status=fs.readFileSync('calendar-status.js','utf8');
const ia=fs.readFileSync('information-architecture.js','utf8');
const iaCss=fs.readFileSync('information-architecture.css','utf8');
const refine=fs.readFileSync('workspace-refinement.js','utf8');
const refineCss=fs.readFileSync('workspace-refinement.css','utf8');
const recipeCosts=fs.readFileSync('recipe-ingredient-costs.js','utf8');
const recipeCostsCss=fs.readFileSync('recipe-ingredient-costs.css','utf8');
const ledger=fs.readFileSync('finance-ledger-detail.js','utf8');
const ledgerCss=fs.readFileSync('finance-ledger-detail.css','utf8');
const html=fs.readFileSync('index.html','utf8');

assert(!ui.includes('toISOString()'),'operations UI must not use UTC ISO conversion for local month boundaries');
assert(ui.includes('monthEnd'),'operations UI must define explicit local month boundary handling');
assert(ui.includes('B.effectiveStatus'),'operations UI must use canonical effective class status');
assert(ops.includes('B.classFinancials'),'class operations must use canonical financial engine');
assert(ops.includes('B.payment'),'class operations must use canonical payment engine');
assert(!ops.includes('function classCosts'),'legacy independent class-cost helper must not return');
assert(!ops.includes('rentForDay'),'legacy independent rent helper must not return');
assert(planner.includes('B.classFinancials'),'calendar planning must use canonical financial engine for scenario profit');
assert(planner.includes('localStorage'),'draft planning must remain separate from schedule until explicitly applied');
assert(planner.includes("mark('schedule')"),'explicit draft apply must use normal schedule persistence flow');
assert(editor.includes("mark('schedule')"),'legacy compatibility class editor must use normal schedule persistence flow');
assert(status.includes('B.payment'),'calendar seat indicators must use canonical payment state');
assert(status.includes('function seatStates'),'calendar status module must calculate one state per recruiting seat');
assert(status.includes("state:'open'")&&status.includes("state:'full'")&&status.includes("state:'paid'"),'calendar seat indicators must preserve empty/booked/paid states');
assert(status.includes('for(let i=0;i<capacity;i++)'),'calendar must render seat state from class capacity');
assert(status.includes('calendar-seat-dots'),'calendar events must render a seat-dot group');
assert(!status.includes('information-architecture.js'),'calendar status must not dynamically load the role-separation runtime a second time');

assert(ia.includes('renderLeanDashboard'),'dashboard must be action-oriented instead of repeating finance summaries');
assert(ia.includes('calendarMonthJump'),'single calendar must support direct navigation across past and future months');
assert(ia.includes('dayOpsModal'),'calendar date click must open the unified day management modal');
assert(ia.includes('data-day-edit'),'day modal must edit scheduled classes without opening a second class popup');
assert(ia.includes('data-person="paymentStatus"'),'day modal must manage participant payment state in the same popup');
assert(ia.includes('data-day-delete'),'day modal must support class deletion');
assert(ia.includes('dayOpsAddClass'),'future/current dates must support new class creation from the same popup');
assert(ia.includes("mark('schedule')"),'calendar day manager must persist through normal schedule persistence');
assert(ia.includes("$('recipeDecision').hidden=true"),'recipe tab must suppress duplicate dashboard-like summary cards');
assert(ia.includes('forecast.hidden=true'),'finance must suppress fixed next-month duplicate forecast');
assert(iaCss.includes('#calendar #calendarClassDetail')&&iaCss.includes('display:none!important'),'inline calendar detail must stay hidden in favor of the single day popup');
assert(iaCss.includes('#dashboard #operationsDashboard'),'legacy repeated dashboard summary must stay hidden');

assert(refine.includes("validCategories=['빵류','디저트류','케이크류']"),'recipe workspace must expose exactly bread, dessert, and cake categories');
assert(refine.includes('recipeCategory'),'recipe workspace must classify recipes');
assert(refine.includes("mark('recipes')"),'manual recipe category changes must persist with recipe data');
assert(refine.includes('data-quick-paid'),'calendar participant rows must expose a direct paid checkbox');
assert(refine.includes("select.value=check.checked?'입금완료':'미입금'"),'paid checkbox must drive the canonical participant payment status');
assert(refine.includes('fill.click()'),'participant rows must auto-fill to the booked student count');
assert(refine.includes('B.payment'),'finance may read canonical payment totals for current or explicitly unpaid classes');
assert(refine.includes('B.classFinancials'),'finance visualization must read canonical revenue/profit calculations');
assert(refine.includes('pastPaymentException')&&refine.includes('past&&!pastPaymentException'),'past classes must default to paid unless an explicit payment exception exists');
assert(refine.includes('collected:f.revenue,outstanding:0,assumed:true'),'past default-paid rule must use full class revenue without fabricating participant rows');
assert(refine.includes('renderOperatingFlow')&&refine.includes('renderCostBreakdown')&&refine.includes('renderProfitBars'),'finance must focus on operating flow, expense mix, and menu profitability');
assert(refine.includes('material=f.material==null?0:num(f.material)')&&refine.includes('rent=num(f.rent)'),'finance must separate operating expense components');
assert(!refine.includes('finance-ring'),'payment-rate ring must not remain the primary finance visualization');
assert(refineCss.includes('.finance-operating-chart')&&refineCss.includes('.finance-cost-bars')&&refineCss.includes('.finance-profit-bars'),'operating finance visual styles must remain available');

assert(recipeCosts.includes('function masterRows'),'recipe ingredient detail must use the shared ingredient price master');
assert(recipeCosts.includes('function usageCalc'),'recipe ingredient detail must calculate cost from recipe amount');
assert(recipeCosts.includes('price_per_100g'),'recipe ingredient detail must use normalized per-100g pricing');
assert(recipeCosts.includes('재료별 계산 합계')&&recipeCosts.includes('저장된 레시피 원가'),'recipe detail must show calculated ingredient sum and stored recipe cost separately');
assert(recipeCosts.includes("'전란':'계란'")&&recipeCosts.includes("'녹인버터':'버터'"),'recipe costing must normalize common recipe ingredient aliases');
assert(recipeCosts.includes("note:'단가 미연결'")||recipeCosts.includes("'단가 미연결'"),'unmatched ingredient prices must remain explicit rather than guessed');
assert(recipeCostsCss.includes('.ingredient-cost-table')&&recipeCostsCss.includes('.ingredient-cost-summary'),'ingredient cost detail styles must remain available');

assert(ledger.includes('B.classFinancials'),'detailed finance ledger must use canonical class financials');
assert(ledger.includes('function classBreakdown')&&ledger.includes('수업별 손익 브레이크다운'),'finance ledger must show per-class revenue/material/rent/other/profit breakdown');
assert(ledger.includes('rentBasis')&&ledger.includes('locationOf'),'class breakdown must explain rent date/location/basis');
assert(ledger.includes('function monthlyTable')&&ledger.includes('원가 연결'),'monthly finance must show exact monthly KRW totals and cost coverage');
assert(ledger.includes('function menuBreakdown')&&ledger.includes('메뉴별 수익성 브레이크다운'),'finance ledger must show menu-level profitability with underlying class dates');
assert(ledger.includes('profitPerPerson')&&ledger.includes('costablePeople'),'finance ledger must keep per-student profitability on the same costable subset as class profit');
assert(ledger.includes('avgClassProfit')&&ledger.includes('avgPersonProfit'),'finance summary must separate per-class and per-student average profit');
assert(ledger.includes('수업 1회당 평균이익')&&ledger.includes('수강생 1명당 평균이익'),'top finance KPIs must surface unit economics at a glance');
assert(ledger.includes('메뉴 1회당 평균이익')&&ledger.includes('수강생 1명당 평균이익'),'menu profitability must distinguish total contribution from per-class and per-student economics');
assert(ledger.includes('회당 이익')&&ledger.includes('인당 이익'),'monthly exact table must include class and student unit profit');
assert(ledgerCss.includes('.ledger-month-table')&&ledgerCss.includes('.ledger-formula')&&ledgerCss.includes('.ledger-menu-classes'),'detailed finance ledger styles must remain available');

assert(html.includes('id="calendarClassDetail"'),'calendar compatibility host must exist for legacy runtime');
assert(!html.includes('<button data-page="schedule">'),'schedule management must not remain a visible navigation destination');
assert(!html.includes('<button data-page="planner">'),'standalone month planner must not remain a visible navigation destination');
assert(html.includes('calendar-status.js'),'calendar status runtime must be loaded');
assert(html.includes('information-architecture.js'),'role-separation runtime must be loaded explicitly');
assert(html.includes('information-architecture.css'),'role-separation styling must be loaded explicitly');
assert(html.includes('workspace-refinement.js'),'recipe/payment/finance refinement runtime must be loaded explicitly');
assert(html.includes('workspace-refinement.css'),'recipe/payment/finance refinement styles must be loaded explicitly');
assert(html.includes('recipe-ingredient-costs.js'),'recipe ingredient cost runtime must be loaded explicitly');
assert(html.includes('recipe-ingredient-costs.css'),'recipe ingredient cost styles must be loaded explicitly');
assert(html.includes('finance-ledger-detail.js'),'detailed finance ledger runtime must be loaded explicitly');
assert(html.includes('finance-ledger-detail.css'),'detailed finance ledger styles must be loaded explicitly');
assert(html.includes('재정 · 수익'),'finance tab must be labeled as operating finance');

const order=['app.js','business-engine.js','data-normalization.js','class-ops-canonical.js','business-engine-adapter.js','operations-ui.js','management-planner.js','calendar-class-editor.js','calendar-status.js','information-architecture.js','workspace-refinement.js','recipe-ingredient-costs.js','finance-ledger-detail.js'].map(x=>html.indexOf(x));
assert(order.every(x=>x>=0),'all canonical runtime modules must be loaded');
for(let i=1;i<order.length;i++)assert(order[i]>order[i-1],`runtime script order invalid at position ${i}`);

console.log('runtime architecture tests passed');
