const assert=require('assert');
const fs=require('fs');
const ui=fs.readFileSync('operations-ui.js','utf8');
const ops=fs.readFileSync('class-ops-canonical.js','utf8');
const planner=fs.readFileSync('management-planner.js','utf8');
const editor=fs.readFileSync('calendar-class-editor.js','utf8');
const status=fs.readFileSync('calendar-status.js','utf8');
const ia=fs.readFileSync('information-architecture.js','utf8');
const iaCss=fs.readFileSync('information-architecture.css','utf8');
const refine=fs.readFileSync('workspace-refinement.js','utf8');
const refineCss=fs.readFileSync('workspace-refinement.css','utf8');
const recipeCosts=fs.readFileSync('recipe-ingredient-costs.js','utf8');
const recipeCostsCss=fs.readFileSync('recipe-ingredient-costs.css','utf8');
const ledger=fs.readFileSync('finance-ledger-detail.js','utf8');
const ledgerCss=fs.readFileSync('finance-ledger-detail.css','utf8');
const html=fs.readFileSync('index.html','utf8');

assert(!ui.includes('toISOString()'),'operations UI must not use UTC ISO conversion for local month boundaries');
assert(ui.includes('monthEnd'),'operations UI must define explicit local month boundary handling');
assert(ui.includes('B.effectiveStatus'),'operations UI must use canonical effective class status');
assert(ops.includes('B.classFinancials'),'class operations must use canonical financial engine');
assert(ops.includes('B.payment'),'class operations must use canonical payment engine');
assert(!ops.includes('function classCosts'),'legacy independent class-cost helper must not return');
assert(!ops.includes('rentForDay'),'legacy independent rent helper must not return');
assert(planner.includes('B.classFinancials'),'calendar planning must use canonical financial engine for scenario profit');
assert(planner.includes('localStorage'),'draft planning must remain separate from schedule until explicitly applied');
assert(planner.includes("mark('schedule')"),'explicit draft apply must use normal schedule persistence flow');
assert(editor.includes("mark('schedule')"),'legacy compatibility class editor must use normal schedule persistence flow');
assert(status.includes('B.payment'),'calendar seat indicators must use canonical payment state');
assert(status.includes('function seatStates'),'calendar status module must calculate one state per recruiting seat');
assert(status.includes("state:'open'")&&status.includes("state:'full'")&&status.includes("state:'paid'"),'calendar seat indicators must preserve empty/booked/paid states');
assert(status.includes('for(let i=0;i<capacity;i++)'),'calendar must render seat state from class capacity');
assert(status.includes('calendar-seat-dots'),'calendar events must render a seat-dot group');
assert(!status.includes('information-architecture.js'),'calendar status must not dynamically load information architecture');

assert(ia.includes('renderLeanDashboard'),'dashboard must stay action-oriented');
assert(ia.includes('calendarMonthJump'),'single calendar must support direct month navigation');
assert(ia.includes('dayOpsModal'),'calendar date click must open the unified day manager');
assert(ia.includes('data-day-edit'),'day manager must edit classes without a second popup');
assert(ia.includes('data-person="paymentStatus"'),'day manager must keep canonical participant payment state');
assert(ia.includes('data-day-delete'),'day manager must support class deletion');
assert(ia.includes('dayOpsAddClass'),'day manager must support class creation');
assert(ia.includes("mark('schedule')"),'calendar changes must persist through schedule data');
assert(ia.includes("$('recipeDecision').hidden=true"),'recipe tab must suppress dashboard-like summaries');
assert(iaCss.includes('#calendar #calendarClassDetail')&&iaCss.includes('display:none!important'),'duplicate inline calendar detail must remain hidden');
assert(iaCss.includes('#dashboard #operationsDashboard'),'legacy repeated dashboard must remain hidden');

assert(refine.includes("validCategories=['빵류','디저트류','케이크류']"),'recipes must expose bread, dessert, and cake categories');
assert(refine.includes('recipeCategory'),'recipe category logic must remain available');
assert(refine.includes("mark('recipes')"),'manual recipe category changes must persist');
assert(refine.includes('data-quick-paid'),'participant rows must expose a direct paid checkbox');
assert(refine.includes("select.value=check.checked?'입금완료':'미입금'"),'paid checkbox must drive canonical participant payment status');
assert(refine.includes('fill.click()'),'participant slots must auto-fill to student count');
assert(refine.includes('dayops-advanced'),'class fee/rent/batch settings must be progressively disclosed');
assert(refine.includes('recipe-process-details'),'recipe process must be progressively disclosed');
assert(!refine.includes('renderOperatingFlow'),'workspace refinement must not own a duplicate finance dashboard');
assert(refineCss.includes('.quick-paid-check')&&refineCss.includes('.dayops-advanced'),'calendar minimal controls must remain styled');
assert(refineCss.includes('.recipe-category-bar')&&refineCss.includes('.recipe-process-details'),'recipe category and progressive process styles must remain available');

assert(recipeCosts.includes('function masterRows'),'recipe ingredient detail must use the shared ingredient price master');
assert(recipeCosts.includes('function usageCalc'),'recipe ingredient detail must calculate cost from recipe amount');
assert(recipeCosts.includes('price_per_100g'),'recipe ingredient detail must use normalized per-100g pricing');
assert(recipeCosts.includes('재료별 계산 합계'),'recipe detail must show the ingredient-calculated total');
assert(!recipeCosts.includes('저장된 레시피 원가'),'stored recipe total must not be repeated inside the expanded ingredient detail');
assert(recipeCosts.includes('카드 상단'),'expanded recipe cost detail must point to the single visible owner of total recipe cost');
assert(recipeCosts.includes("'전란':'계란'")&&recipeCosts.includes("'녹인버터':'버터'"),'recipe costing must normalize common aliases');
assert(recipeCosts.includes('단가 미연결'),'unmatched ingredient prices must stay explicit');
assert(recipeCostsCss.includes('.ingredient-cost-table')&&recipeCostsCss.includes('.ingredient-cost-summary'),'ingredient cost detail styles must remain available');

assert(ledger.includes('B.classFinancials'),'finance must use canonical class financials');
assert(ledger.includes('costablePeople'),'finance averages must use only students from costable classes');
assert(ledger.includes('avgClassProfit')&&ledger.includes('avgStudentProfit'),'finance must separate per-class and per-student profit');
assert(ledger.includes("timeZone:'Asia/Seoul'"),'finance current-state cut must use Seoul time');
assert(ledger.includes('function occurred'),'finance must distinguish completed-to-date classes from future current-month classes');
assert(ledger.includes('function flowCard'),'finance must have a reusable current-month flow card');
assert(ledger.includes("flowCard('current'")&&ledger.includes("flowCard('forecast'"),'finance must show current-to-date and current-month forecast side by side');
assert(ledger.includes('재료비')&&ledger.includes('대관비')&&ledger.includes('포장·기타')&&ledger.includes('남는 돈'),'finance flow must expose material, rent, other costs, and remainder');
assert(ledger.includes('회당 남음')&&ledger.includes('인당 남음'),'finance must expose unit economics under the main flow');
assert(ledger.includes('function previousMonths')&&ledger.includes('shiftMonth(cur,-1)'),'month comparison must start at the immediately previous month');
assert(ledger.includes('data-compare-month'),'finance must support direct historical month selection');
assert(ledger.includes('function comparePanel'),'finance must compare current-month forecast against a selected historical month');
assert(ledger.includes('function menuPanel')&&ledger.includes('data-fin-menu'),'current-month menu profitability must remain interactive');
assert(ledger.includes('function classDetails'),'class-level finance evidence must remain progressively disclosed');
assert(!ledger.includes('function moneyFlow('),'legacy selected-period money-flow owner must not return');
assert(!ledger.includes('function monthlyFlowPanel'),'legacy past-first monthly flow list must not return');
assert(ledgerCss.includes('.finance-focus-grid')&&ledgerCss.includes('.focus-flow-card'),'current and forecast cards must share one proportional grid');
assert(ledgerCss.includes('.flow-stack')&&ledgerCss.includes('.flow-legend'),'finance must visualize proportional cost composition');
assert(ledgerCss.includes('.month-selector')&&ledgerCss.includes('.compare-metrics'),'month comparison controls and metrics must remain styled');
assert(ledgerCss.includes('.month-menu-card')&&ledgerCss.includes('.finance-detail-shell'),'menu profitability and collapsed detail styles must remain');

assert(html.includes('id="calendarClassDetail"'),'calendar compatibility host must remain for legacy runtime');
assert(!html.includes('<button data-page="schedule">'),'schedule must not return as a visible nav destination');
assert(!html.includes('<button data-page="planner">'),'planner must not return as a visible nav destination');
assert(html.includes('calendar-status.js'),'calendar status runtime must load');
assert(html.includes('information-architecture.js'),'information architecture runtime must load');
assert(html.includes('workspace-refinement.js'),'workspace refinement runtime must load');
assert(html.includes('recipe-ingredient-costs.js'),'recipe ingredient costing runtime must load');
assert(html.includes('finance-ledger-detail.js'),'finance decision runtime must load');
assert(html.includes('finance-ledger-detail.css'),'finance decision styles must load');
assert(html.includes('재정 · 수익'),'finance tab must retain operating-finance labeling');

const order=['app.js','business-engine.js','data-normalization.js','class-ops-canonical.js','business-engine-adapter.js','operations-ui.js','management-planner.js','calendar-class-editor.js','calendar-status.js','information-architecture.js','workspace-refinement.js','recipe-ingredient-costs.js','finance-ledger-detail.js'].map(x=>html.indexOf(x));
assert(order.every(x=>x>=0),'all canonical runtime modules must be loaded');
for(let i=1;i<order.length;i++)assert(order[i]>order[i-1],`runtime script order invalid at position ${i}`);

console.log('runtime architecture tests passed');